### ISSUE TITLE
Input required and not supplied: token

### ISSUE THREAD

**Issue by kwent** [cplee/github-actions-demo#10]
Running the demo:

```
[CI/test] ⭐  Run actions/checkout@v2
[CI/test]   ☁  git clone 'https://github.com/actions/checkout' # ref=v2
[CI/test]   🐳  docker cp src=/Users/kwent/.cache/act/actions-checkout@v2/ dst=/Users/kwent/Projects/perso/github-actions-demo/_actions/actions-checkout@v2/
[CI/test]   ❓  ::save-state name=isPost,::true
[CI/test]   💬  ::debug::GITHUB_WORKSPACE = '/Users/kwent/Projects/perso/github-actions-demo'
[CI/test]   💬  ::debug::qualified repository = 'cplee/github-actions-demo'
[CI/test]   💬  ::debug::ref = 'refs/heads/master'
[CI/test]   💬  ::debug::commit = '5c6f585b1f9d8526c8e1672c5f8f00883b895d93'
[CI/test]   💬  ::debug::clean = true
[CI/test]   💬  ::debug::fetch depth = 1
[CI/test]   💬  ::debug::lfs = false
[CI/test]   💬  ::debug::submodules = false
[CI/test]   💬  ::debug::recursive submodules = false
[CI/test]   ❗  ::error::Input required and not supplied: token
[CI/test]   ❌  Failure - actions/checkout@v2
Error: exit with `FAILURE`: 1
```

**Comment by catthehacker** [comment]
Fixed in https://github.com/nektos/act/pull/680
Ref: https://github.com/nektos/act/issues/678

**Comment by iaperri** [comment]
Sorry to bother here @catthehacker, but I'm still having this issue in my mac and in linux. Both running with the latest act version 0.2.22

**Comment by catthehacker** [comment]
Because it's broken in `0.2.22`, there wasn't a new release yet
